services:
  frontend:
    container_name: schedule_frontend
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - .:/workspace
      - /workspace/frontend/node_modules
    environment:
      #ホットリロードの有効化
      - CHOKIDAR_USEPOLLING=true
      #ホットリロードが上手くいかないときに有効にすると一定時間にファイルの確認をしてくれる
      #- WATCHPACK_POLLING=true
    #working_dirのパスをサービスごとに統一
    working_dir: /workspace/frontend
    command: npm run dev
    #フロントエンドはバックエンドに依存しているため、バックエンドを先に起動する（※厳密な制御ではconditionでhealthyを指定しバックエンドの起動完了を確認するが、今回は簡略化のためにdepends_onのみで制御する）
    depends_on:
      - backend

  backend:
    container_name: schedule_backend
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - .:/workspace
    #working_dirのパスをサービスごとに統一
    working_dir: /workspace/backend
    command: python app/app.py
    #バックエンドはpostgresに依存しているため、postgresを先に起動する（※（※厳密な制御ではconditionでhealthyを指定しDBの起動完了を確認するが、今回は簡略化のためにdepends_onのみで制御する）
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "schedule_manager"
    # (※ 厳密にはhealthcheckを指定して、コンテナの起動後にDBが利用可能になるまで待機する必要があるが、今回は簡略化のために省略する)

volumes:
  postgres_data:
