services:
  frontend:
    container_name: schedule_frontend
    build: ./frontend
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      #ホットリロードの有効化
      - CHOKIDAR_USEPOLLING=true
      #ホットリロードが上手くいかないときに有効にすると一定時間にファイルの確認をしてくれる
      #- WATCHPACK_POLLING=true

  backend:
    build: ./backend
    ports:
      - 5173:5173
    container_name: schedule_backend

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "schedule_manager"

volumes:
  postgres_data:
